project_id = "kaopnizsbkzxqdzmocwa"

[functions.webhook-n8n]
verify_jwt = false

[functions.extract-case-data]
verify_jwt = false

[functions.generate-documents]
verify_jwt = false

[functions.webhook-resend-inbound]
verify_jwt = false

[functions.pre-extract-cpf]
verify_jwt = false

[functions.merge-casos]
verify_jwt = false

[functions.process-contracheques-pdf]
verify_jwt = false

[functions.process-documentos-pessoais-pdf]
verify_jwt = false
